services:
  postgres:
    image: postgres:16
    container_name: job-tracker-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_tracker
    volumes:
      - job-tracker-postgres-data:/var/lib/postgresql/data
    networks:
      - job-tracker-network

  redis:
    image: redis:7-alpine
    container_name: job-tracker-redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - job-tracker-redis-data:/data
    networks:
      - job-tracker-network

volumes:
  job-tracker-postgres-data:
    name: job-tracker-postgres-data
    external: true
  job-tracker-redis-data:
    name: job-tracker-redis-data

networks:
  job-tracker-network:
    name: job-tracker-network
    external: true
